## Credit Risk Model (CRM) Data Preprocessing

In [185]:
import numpy as np

In [186]:
np.set_printoptions(suppress = True, linewidth= 100, precision =2)

## Importing the Data

In [187]:
raw_data_np =np.genfromtxt('loan-data.csv', delimiter= ';', skip_header = 1, autostrip= True)
raw_data_np_copy=raw_data_np.copy()
raw_data_np_copy

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [188]:
np.isnan(raw_data_np_copy).sum()

88005

In [189]:
temporary_fill=np.nanmax(raw_data_np_copy).round(2)+1 # filler for all the missing entries in the dataset
temporary_mean=np.nanmean(raw_data_np_copy, axis=0) # hold the means for every column

<ipython-input-189-eebecdd0c712>:2: RuntimeWarning: Mean of empty slice
  temporary_mean=np.nanmean(raw_data_np_copy, axis=0) # hold the means for every column


In [190]:
temporary_fill

68616520.0

In [191]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [192]:
temporary_statistics= np.array([np.nanmin(raw_data_np_copy, axis=0), # min for every column
                               temporary_mean, # mean for every column
                               np.nanmax(raw_data_np_copy, axis=0)]) # max for every column
temporary_statistics
# The "nan" indicates there are 8 columns full of strings,
#hence we should split the array into two smaller arrays (numeric values & string values)

<ipython-input-192-efc4fceb2c25>:1: RuntimeWarning: All-NaN slice encountered
  temporary_statistics= np.array([np.nanmin(raw_data_np_copy, axis=0), # min for every column
<ipython-input-192-efc4fceb2c25>:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np_copy, axis=0)]) # max for every column


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [193]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [194]:
np.isnan(temporary_mean)

array([False,  True, False,  True, False,  True, False, False,  True,  True,  True,  True,  True,
       False])

In [195]:
np.isnan(temporary_mean)== False

array([ True, False,  True, False,  True, False,  True,  True, False, False, False, False, False,
        True])

In [196]:
## To get the indices of the columns which only contain strings
columns_strings=np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings
# if the column  contains only text, then its mean will yield 'nan',
# hence (isnan) will return "True" for that column,
# knowing that the returned "True" is different from 0 [the default condition for the (argwhere)],
# then (argwhere) returns the index of the column

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [197]:
## To get the indices of the columns which only contain numeric values
columns_numeric=np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric
# if the column  contains numeric values, then its mean will not yield 'nan',
# hence (isnan) will return "True" for that column,
# knowing that the returned "True" is different from 0 [the default condition for the (argwhere)],
# then (argwhere) returns the index of the column

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [198]:
loan_data_strings =np.genfromtxt('loan-data.csv',
                                 delimiter= ';',
                                 skip_header = 1,
                                 autostrip= True,
                                 usecols= columns_strings,
                                 dtype='str')
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [199]:
loan_data_numeric =np.genfromtxt('loan-data.csv',
                                 delimiter= ';',
                                 skip_header = 1,
                                 autostrip= True,
                                 usecols= columns_numeric,
                                 filling_values= temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [200]:
header_names =np.genfromtxt('loan-data.csv',
                                 delimiter= ';',
                                 skip_footer = raw_data_np_copy.shape[0], # To obtain the headers, skip the number of rows
                                 autostrip= True,
                                 dtype='str')
header_names

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [201]:
#splitting the headers into two variables holding the names of the columns that contain string data or numeric data
header_strings, header_numeric = header_names[columns_strings], header_names[columns_numeric]

In [202]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [203]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [204]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [205]:
checkpoint_test= checkpoint("checkpoint-test", header_strings, loan_data_strings)

In [206]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [207]:
# to check the accuracy of the checkpoint created
np.array_equal(checkpoint_test['data'],loan_data_strings)

True

## Manipulating String Columns

In [208]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [209]:
#changing the header
header_strings[0]= "issue_date"

In [210]:
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date

In [211]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [212]:
# we can remove the hyphen and the year since all of the issue date is from the year 2015
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0], "-15")

In [213]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [214]:
#converting months into numbers
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
# adding empty space before jan to account for missing values

In [215]:
for i in range(13): # from 0 to 12, swap empty values with 0
        loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == months[i],
                                          i,
                                          loan_data_strings[:,0])

In [216]:
np.unique(loan_data_strings[:,0])
# no more empty spaces as it was swapped with zero

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [217]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [218]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [219]:
# To get the number of unique elements in the column.size
np.unique(loan_data_strings[:,1]).size

9

In [220]:
# According to the data set, it is important to know if the applicant is in a stable financial condtion,
# hence no need to assign different number to each different category out of the 9,
# instead we can make the column as a dummy variable which indicates whether the applicant is in a good/bad economic state,
# Group all different categories into either "good = 1" or "bad = 0"
# good = current, fully paid, in grace period, issued, late(16-30 days) as it indicates he pays after getting his monthly salary
# bad = charged off, default, empty data, Late(31-120 days)

In [221]:
# Creating a bad status array
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [222]:
# if the first column of loan data string IS IN the status bad array created, assign a 0, if not assign 1
loan_data_strings[:,1]=np.where(np.isin(loan_data_strings[:,1], status_bad),0,1)

In [223]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [224]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [225]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [226]:
# Removing months as it is repeated
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2], " months")
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [227]:
# Renaming the column to indicate the numbers properly
header_strings[2]="term_months"

In [228]:
# we assign '60' to missing values because in Credit Risk Modelling (CRM), we have to assume the worst
loan_data_strings[:,2]=np.where(loan_data_strings[:,2] == '','60', loan_data_strings[:,2])
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [229]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [230]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [231]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [232]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Sub Grade

In [233]:
# we can assign appropriate values for empty cells in the "sub-grade" column as it is related to the "Grade" column
# first condition check whether the value in "sub grade" column is missing,
# second condition indicates that in case the 1st condition is staisfied then,
# it checks whether the value in the "grade" column is equal to the value of the iterator variable for the given pass of the loop
# then is assigns the lowest/worst 5th sub-grade of that grade,
# for example, if there is missing value in the column "Sub-grade", then check its corresponding value in the "grade" column (B)
# then assign (B5) to that missing value

for i in np.unique(loan_data_strings[:,3])[1:]: # loops goes through alll the unique grades after the first one (the empty space)
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i + '5',
                                      loan_data_strings[:,4])

In [234]:
# There are still (9) rows in the column where we have neither the "sub-grade" nor the "grade"
# since there are 10,000 values in the columns, those 9 values can be dropped.
# However, since the applicant is withholding information, he/she should be penalized ( as the forms are filled manually by the applicants)
# Hence, we are going to creat a new sub-grade that is even lower than G5 for those applicants
np.unique(loan_data_strings[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [235]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == ''),
                                      "H1",
                                      loan_data_strings[:,4])

In [236]:
np.unique(loan_data_strings[:,4], return_counts = True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

#### Removing Grade

In [237]:
# we can remove the "grade" column as all the information in it is already available in the "sub-grade" column
loan_data_strings=np.delete(loan_data_strings, 3, axis=1)

In [238]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [239]:
# we will delete the header as well
header_strings=np.delete(header_strings, 3)

In [240]:
header_strings[3]

'sub_grade'

#### Converting Sub Grade

In [241]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [242]:
# to avoid using "where" manually multiple times
keys = list(np.unique(loan_data_strings[:,3])) # every key is unique sub-grade represented as a string                         
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0] + 1)) # the value is a rank of trustworthiness, we add + 1 to make it 37 instead of 36 to account for the (range) as it is closed-open, which means it doesnt include the upper limit
dict_sub_grade = dict(zip(keys, values))

In [243]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [244]:
# To convert the Letters into rankings
for i in np.unique(loan_data_strings[:,3]):
        loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i, 
                                          dict_sub_grade[i],
                                          loan_data_strings[:,3])

In [245]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [246]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [247]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [248]:
# Assign bad/0 to empty spaces and not verified & good/1 to Source verified and verified
loan_data_strings[:,4]=np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'), 0 , 1)

In [249]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [250]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [251]:
# Remove the repeating part of the url,
loan_data_strings[:,5]=np.chararray.strip(loan_data_strings[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [252]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [253]:
# Those numbers look like the same number in the first "id" column
np.array_equal(loan_data_numeric[:,0].astype(dtype="int32"), loan_data_strings[:,5].astype(dtype="int32"))

True

In [254]:
# The URL column does not contain any information that can't be extracted from the "id" column, hence we can delete it
loan_data_strings=np.delete(loan_data_strings,5, axis =1)
header_strings=np.delete(header_strings,5)

In [255]:
# to check it is deleted properly
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

### State Address

In [256]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [262]:
header_strings[5]= "state_address"

In [263]:
np.unique(loan_data_strings[:,5], return_counts= True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [265]:
# To display the state according to the number of applicant
states_names, states_count = np.unique(loan_data_strings[:,5], return_counts= True)
states_count_sorted=np.argsort(-states_count) # we add minus to sort in decreasing order
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [266]:
# assign 0 for missing data to avoid biasing with variable coefficient by excluding applicants that are not attributed to a speicif state from any region
loan_data_strings[:,5]=np.where(loan_data_strings[:,5]== '', 0, loan_data_strings[:,5])

In [267]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [268]:
# converting string data into numeric values stored as text
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], states_west), 1 , loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], states_south), 2 , loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], states_midwest), 3 , loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5], states_east), 4  , loan_data_strings[:,5])

In [269]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [270]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [273]:
#converting the numbers in string format into integer format
loan_data_strings=loan_data_strings.astype("int")

In [274]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [275]:
checkpoint_strings=checkpoint("Checkpoint-Strings", header_strings, loan_data_strings)

In [276]:
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [277]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [278]:
np.array_equal(checkpoint_strings["data"], loan_data_strings)

True

## Manipulating Numeric Columns

In [279]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [280]:
np.isnan(loan_data_numeric).sum()

0

### Substitute "Filler" Values

In [281]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [282]:
temporary_fill

68616520.0

In [284]:
# to check whether there are any "temporary fill" values in the id column
np.isin(loan_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [285]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum()
# The outcome is 0 (total number of true),
# This means that we haven't had to fill any missing values with the "temporary fill" in this column

0

In [289]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Temporary Stats

In [287]:
# 1st row= min = index [0]
# 2nd row = mean = index[1]
# 3rd row = max = index[2]
temporary_statistics[:, columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [288]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [290]:
# Assign minimum data for the temporary fill values in the (funded amount) column
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill, 
                                  temporary_statistics[0, columns_numeric[2]], # 0 indicates the 1st row = min , columns_numeric to avoid choosing from the string columns in the temporary statistics
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

**Loaned Amount, Interest Rate, Total Payment, Installment

In [291]:
# Assign maximum data for the temporary fill values in the (Loaned Amount, Interest Rate, Total Payment, Installment) columns
for i in [1,3,4,5]: # indices of the columns
    loan_data_numeric[:,i]= np.where(loan_data_numeric[:,i]==temporary_fill,
                                    temporary_statistics[2, columns_numeric[i]], # index 2 to assing the 3rd row = max
                                    loan_data_numeric[:,i])

In [292]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Currency Change

**The Exchange Rate

In [296]:
# we will use the numbers from the 4th column (adjusted closing prices)
EUR_USD=np.genfromtxt("EUR-USD.csv", delimiter=',', autostrip=True, skip_header=1, usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [297]:
# months
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [298]:
exchange_rate=loan_data_strings[:,0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1], #indexing start from 0
                             exchange_rate)   
    exchange_rate = np.where(exchange_rate == 0, # for missing values, assign the mean
                             np.mean(EUR_USD), 
                             exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [299]:
exchange_rate.shape

(10000,)

In [300]:
loan_data_numeric.shape

(10000, 6)

In [301]:
exchange_rate=np.reshape(exchange_rate, (10000,1))

In [303]:
loan_data_numeric=np.hstack((loan_data_numeric,exchange_rate))

In [304]:
# used array to turn text(zero dimension scalar) into array(one dimension vector)
header_numeric=np.concatenate((header_numeric,np.array(['exchange_rate']))) 
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [305]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [306]:
columns_dollar=np.array([1,2,4,5]) # indices of columns with dollar sign

In [307]:
loan_data_numeric[:,[columns_dollar]] # to show those specific columns only

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [308]:
# 6th index is for the exchange rate which we divide by
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))

In [310]:
loan_data_numeric.shape

(10000, 11)

In [311]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

#### Expanding the header

In [312]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [313]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [315]:
header_numeric=np.concatenate((header_numeric,header_additional))

In [316]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [317]:
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

In [318]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [319]:
# Reordering
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [321]:
header_numeric=header_numeric[columns_index_order]

In [322]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [324]:
loan_data_numeric=loan_data_numeric[:,columns_index_order]

### Interest Rate

In [325]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [326]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [328]:
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100

In [329]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [330]:
checkpoint_numeric=checkpoint("Checkpoint-Numeric", header_numeric, loan_data_numeric)

In [331]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [333]:
loan_data_strings.shape

(10000, 6)

In [334]:
loan_data_numeric.shape

(10000, 11)

In [337]:
loan_data=np.hstack((loan_data_numeric,loan_data_strings))

In [338]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [339]:
np.isnan(loan_data).sum()

0

In [341]:
header_full = np.concatenate((header_numeric, header_strings))

## Sorting the New Dataset

In [346]:
loan_data=loan_data[np.argsort(loan_data[:,0])] #based on the id column

In [347]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [348]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

## Storing the New Dataset

In [350]:
loan_data=np.vstack((header_full, loan_data))

In [352]:
np.savetxt("Preprocessing-Project.csv", loan_data, fmt="%s", delimiter=',')